version: '2.1'
services:
    eureka:
      build: eureka-server/
      #healthcheck:
        #test: curl -f https://localhost:8761 || exit 1
        #interval: 1m30s
        #timeout: 10s
        #retries: 3
      ports:
        - '8761:8761'

    product-service:
      build: product-service/
      restart: always
      environment:
        - spring.profiles.active=docker
      #depends_on:
        #eureka:
          #condition: service_healthy
      ports:
        - '8082:8082'

    gateway-painel-produtos:
      build: product-service/
      environment:
        - spring.profiles.active=docker
      depends_on:
        - eureka
        #eureka:
          #condition: service_healthy
      ports:
        - '8080:8080'

    turbine:
      build: turbine-service/
      environment:
        - spring.profiles.active=docker
      depends_on:
        - eureka
        #eureka:
          #condition: service_healthy
      ports:
        - '8989:8989'
