version: '2'
services:
    eureka:
      build: eureka-server/
      container_name: eureka
      hostname: eureka-server
      networks:
        - 'discovery'
      ports:
        - '8761:8761'

    config:
      build: config-server/
      container_name: config-server
      hostname: config-server
      networks:
        - 'discovery'
      ports:
        - '8888:8888'

    product-service:
      build: product-service/
      container_name: product-service
      hostname: product-service
      restart: always
      environment:
        - spring.profiles.active=docker
      depends_on:
        - eureka
          #condition: service_healthy
      container_name: product-service
      networks:
        - 'discovery'
      ports:
        - '8082:8082'

    gateway-painel-produtos:
      build: gateway-painel-produtos/
      container_name: gateway-painel-produtos
      hostname: gateway-painel-produtos
      environment:
        - spring.profiles.active=docker
      depends_on:
        - eureka
      networks:
        - 'discovery'
      ports:
        - '8080:8080'

    turbine:
      build: turbine-service/
      container_name: turbine-service
      hostname: turbine-service
      environment:
        - spring.profiles.active=docker
      depends_on:
        - eureka
      ports:
        - '8989:8989'

networks:
  discovery:
