turbine:
  appConfig: gateway-painel-produtos
  aggregator:
    cluster-config: gateway-painel-produtos
  InstanceMonitor:
    eventStream:
      skipLineLogic:
        enabled: false

logging:
  level: INFO

management.security.enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
#spring:
#  boot:
#    admin:
#      routes:
#        endpoints: env,metrics,dump,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream


---
spring:
  profiles: docker
  boot:
      admin:
        routes:
          endpoints: env,metrics,dump,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream


eureka:
 instance:
   hostname: turbine-service
   prefer-ip-address: true
 client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
           defaultZone: http://eureka-server:8761/eureka/

turbine:
  appConfig: product-service, gateway-painel-produtos
  aggregator:
    cluster-config: product-service, gateway-painel-produtos
