server:
  port: 8989

turbine:
  appConfig: product-service, gateway-painel-produtos

logging:
  level: INFO

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/