eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring.boot.admin.url: http://localhost:8989

management.security.enabled: false

---
spring:
  profiles: docker

eureka:
  instance:
    hostname: product-service
  client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
           defaultZone: http://eureka-server:8761/eureka/
endpoints:
 shutdown:
    enabled: true

spring.boot.admin.url: http://turbine-service:8989

management.security.enabled: false