server:
  port: 8888

spring.boot.admin.url: http://localhost:8989

management.security.enabled: false

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OliveiraMaicon/config-repository.git
  application:
      name: config-server
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix


---
spring:
  profiles: docker
  application:
    name: config-server

server:
  port: 8888

eureka:
  instance:
    hostname: config-server
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/